import html from "html-literal";

export default () => html`
  <section id="events">
    <header>EVENTS</header>
    <h1>
      ALL EVENTS (COMMAND SPONSORED OR PRIVATE) MUST BE SUBMITTED TO THE VISITOR
      CONTROL CENTER NO LONGER THAN 14 BUSINESS DAYS PRIOR TO THE EVENT! <br />
      EVENTS SUBMITTED SHORTER THAN 14 DAYS ARE NOT GUARANTEED APPROVAL.
    </h1>

    <p>
      THE EVENT INFORMATION SHOULD BE SUBMITTED IN MEMO FORMAT TO
      NASO.PASSOFFICE@NAVY.MIL
    </p>
    <p>
      INDIVIDUALS 18 AND UP THAT WILL BE IN ATTENDANCE WILL NEED THEIR NAMES AND
      DRIVER'S LICENSE NUMBER INCLUDED ON THE MEMO.
    </p>
    <p>
      THE MAIN POINT OF CONTACT FOR THE EVENT WILL BE INFORMED IF CERTAIN GUESTS
      DO NOT MEET THE REQUIREMENTS TO OBTAIN ACCESS TO THE BASE.
    </p>
  </section>
`;
